services:
  auth:
    image: authimg
    container_name: authcntr
    build: ./backend/AUTH
    networks:
      - net1
    init: true
  nginx:
    image: nginximg
    container_name: nginxcntr
    build: ./reverseproxy
    networks:
      - net1
    init: true
    depends_on:
      - auth
    ports:
      - '22222:80'
networks:
  net1:
    name: network1