services:
  nginx:
    image: nginximg
    container_name: nginxcntr
    build: ./reverseproxy
    networks:
      - net1
    init: true
    depends_on:
      - auth
    ports:
      - '9000:80'
    volumes:
      - /home/zasabri/Desktop/actfree/frontend/:/usr/share/nginx/html/

  auth:
    image: authimg
    container_name: authcntr
    build: ./backend/AUTH
    networks:
      - net1
    init: true
    # volumes:
    #   - /home/zasabri/Desktop/actfree/backend/AUTH:/work/
networks:
  net1:
    name: network1